name: github-action
on:
  push:
    branches:
      # When someone push to `main` branch
      - main
jobs:
  
  # test:
  #   ...
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      
      - name: Checkout the repo on the Staging Server
        run: ssh staging "git pull https://github.com/umars-cloudworld/nodejs-githubactions.git || true"
           
      - name: Install
        run: ssh staging 'cd rdicidr && npm install -y'

      - name: Lint
        run: ssh staging 'cd rdicidr && npm run lint'

      - name: Kill previous Node
        run: ssh staging 'sudo killall node' 

      - name: Start the app
        timeout-minutes: 1 # Times out after 1 minute
        run: ssh staging 'cd rdicidr && npm run start&'
